// ADIFParserTests.swift
// HamStationKit — Comprehensive ADIF 3.1 parser and exporter tests
//
// Target: 100+ tests covering parsing, export, date handling, edge cases,
// error handling, round-trip fidelity, and performance.

import XCTest
import Foundation
@testable import HamStationKit

// MARK: - Basic Parsing

class ADIFBasicParsingTests: XCTestCase {

    func testParseSingleQSO() {
        let adif = "<CALL:4>W1AW <BAND:3>20m <MODE:3>FT8 <QSO_DATE:8>20240315 <TIME_ON:6>143022 <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
        XCTAssertEqual(result.records[0]["CALL"], "W1AW")
        XCTAssertEqual(result.records[0]["BAND"], "20m")
        XCTAssertEqual(result.records[0]["MODE"], "FT8")
        XCTAssertEqual(result.records[0]["QSO_DATE"], "20240315")
        XCTAssertEqual(result.records[0]["TIME_ON"], "143022")
        XCTAssertNil(result.header)
        XCTAssertTrue(result.errors.isEmpty)
    }

    func testParseAllCommonFields() {
        let adif = """
        <CALL:4>W1AW <BAND:3>20m <MODE:3>FT8 <FREQ:8>14.07400 \
        <QSO_DATE:8>20240315 <TIME_ON:6>143022 <TIME_OFF:6>143052 \
        <RST_SENT:3>-10 <RST_RCVD:3>-08 <TX_PWR:2>50 \
        <GRIDSQUARE:4>FN31 <NAME:8>John Doe <QTH:9>Newington \
        <COMMENT:11>Good signal <COUNTRY:3>USA <CQZ:1>5 <ITUZ:1>8 \
        <DXCC:3>291 <CONT:2>NA <EOR>
        """
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
        let r = result.records[0]
        XCTAssertEqual(r["CALL"], "W1AW")
        XCTAssertEqual(r["FREQ"], "14.07400")
        XCTAssertEqual(r["TX_PWR"], "50")
        XCTAssertEqual(r["GRIDSQUARE"], "FN31")
        XCTAssertEqual(r["NAME"], "John Doe")
        XCTAssertEqual(r["QTH"], "Newington")
        XCTAssertEqual(r["COMMENT"], "Good signal")
        XCTAssertEqual(r["COUNTRY"], "USA")
        XCTAssertEqual(r["CQZ"], "5")
        XCTAssertEqual(r["ITUZ"], "8")
        XCTAssertEqual(r["DXCC"], "291")
        XCTAssertEqual(r["CONT"], "NA")
        XCTAssertEqual(r["TIME_OFF"], "143052")
    }

    func testParseHeaderAndMultipleRecords() {
        let adif = """
        Generated by TestApp
        <ADIF_VER:5>3.1.4
        <PROGRAMID:7>TestApp
        <PROGRAMVERSION:3>1.0
        <EOH>
        <CALL:4>W1AW <BAND:3>20m <MODE:3>FT8 <QSO_DATE:8>20240315 <TIME_ON:6>143022 <EOR>
        <CALL:5>VE3AB <BAND:3>40m <MODE:2>CW <QSO_DATE:8>20240315 <TIME_ON:6>150000 <EOR>
        <CALL:5>G3XYZ <BAND:3>20m <MODE:3>SSB <QSO_DATE:8>20240316 <TIME_ON:6>081500 <EOR>
        """
        let result = ADIFParser.parse(string: adif)
        XCTAssertNotNil(result.header)
        XCTAssertEqual(result.header?["ADIF_VER"], "3.1.4")
        XCTAssertEqual(result.header?["PROGRAMID"], "TestApp")
        XCTAssertEqual(result.header?["PROGRAMVERSION"], "1.0")
        XCTAssertEqual(result.records.count, 3)
        XCTAssertEqual(result.records[0]["CALL"], "W1AW")
        XCTAssertEqual(result.records[1]["CALL"], "VE3AB")
        XCTAssertEqual(result.records[2]["CALL"], "G3XYZ")
    }

    func testParseHeaderFields() {
        let adif = "<ADIF_VER:5>3.1.4\n<PROGRAMID:6>WSJT-X\n<PROGRAMVERSION:5>2.7.0\n<EOH>\n"
        let result = ADIFParser.parse(string: adif)
        XCTAssertNotNil(result.header)
        XCTAssertEqual(result.header?["ADIF_VER"], "3.1.4")
        XCTAssertEqual(result.header?["PROGRAMID"], "WSJT-X")
        XCTAssertEqual(result.header?["PROGRAMVERSION"], "2.7.0")
        XCTAssertTrue(result.records.isEmpty)
    }

    func testParseTwoRecordsBackToBack() {
        let adif = "<CALL:4>W1AW <EOR><CALL:5>VE3AB <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 2)
        XCTAssertEqual(result.records[0]["CALL"], "W1AW")
        XCTAssertEqual(result.records[1]["CALL"], "VE3AB")
    }

    func testParseSubMode() {
        let adif = "<CALL:4>W1AW <MODE:3>FT8 <SUBMODE:4>FT8+ <BAND:3>20m <QSO_DATE:8>20240315 <TIME_ON:6>143022 <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records[0]["SUBMODE"], "FT8+")
    }
}

// MARK: - Field Handling

class ADIFFieldHandlingTests: XCTestCase {

    func testCaseInsensitiveFieldNames() {
        let adif = "<call:4>W1AW <Band:3>20m <MODE:3>FT8 <Qso_Date:8>20240315 <time_on:6>143022 <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
        XCTAssertEqual(result.records[0]["CALL"], "W1AW")
        XCTAssertEqual(result.records[0]["call"], "W1AW")
        XCTAssertEqual(result.records[0]["Call"], "W1AW")
        XCTAssertEqual(result.records[0]["BAND"], "20m")
        XCTAssertEqual(result.records[0]["QSO_DATE"], "20240315")
    }

    func testFieldWithTypeIndicator() {
        let adif = "<CALL:4:S>W1AW <QSO_DATE:8:D>20240315 <FREQ:8:N>14.07400 <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
        XCTAssertEqual(result.records[0]["CALL"], "W1AW")
        let callField = result.records[0].field(named: "CALL")
        XCTAssertEqual(callField?.typeIndicator, "S")
        let dateField = result.records[0].field(named: "QSO_DATE")
        XCTAssertEqual(dateField?.typeIndicator, "D")
        let freqField = result.records[0].field(named: "FREQ")
        XCTAssertEqual(freqField?.typeIndicator, "N")
    }

    func testFieldLengthShorterThanData() {
        let adif = "<CALL:3>W1AW <BAND:3>20m <EOR>"
        let result = ADIFParser.parse(string: adif, mode: .lenient)
        XCTAssertEqual(result.records.count, 1)
        XCTAssertEqual(result.records[0]["CALL"], "W1A")
    }

    func testFieldLengthLongerThanData() {
        let adif = "<CALL:10>W1AW"
        let result = ADIFParser.parse(string: adif, mode: .lenient)
        XCTAssertTrue(result.records.isEmpty || result.records[0]["CALL"] == "W1AW")
    }

    func testAppFieldsPreserved() {
        let adif = "<CALL:4>W1AW <APP_HAMRD_QSO_ID:5>12345 <APP_N1MM_POINTS:1>2 <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
        XCTAssertEqual(result.records[0]["APP_HAMRD_QSO_ID"], "12345")
        XCTAssertEqual(result.records[0]["APP_N1MM_POINTS"], "2")
        XCTAssertTrue(result.records[0].hasField("APP_HAMRD_QSO_ID"))
        XCTAssertTrue(result.records[0].hasField("APP_N1MM_POINTS"))
    }

    func testUnknownFieldsPreserved() {
        let adif = "<CALL:4>W1AW <TOTALLY_UNKNOWN_FIELD:5>hello <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
        XCTAssertEqual(result.records[0]["TOTALLY_UNKNOWN_FIELD"], "hello")
    }

    func testEmptyFieldValue() {
        let adif = "<CALL:4>W1AW <COMMENT:0> <BAND:3>20m <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
        XCTAssertEqual(result.records[0]["COMMENT"], "")
        XCTAssertTrue(result.records[0].hasField("COMMENT"))
    }

    func testFieldNameUppercase() {
        let field = ADIFField(name: "call", value: "W1AW")
        XCTAssertEqual(field.name, "CALL")
    }

    func testFieldEquality() {
        let a = ADIFField(name: "CALL", value: "W1AW", typeIndicator: "S")
        let b = ADIFField(name: "call", value: "W1AW", typeIndicator: "S")
        XCTAssertEqual(a, b)
    }

    func testFieldHashing() {
        let a = ADIFField(name: "CALL", value: "W1AW")
        let b = ADIFField(name: "call", value: "W1AW")
        var set: Set<ADIFField> = [a]
        set.insert(b)
        XCTAssertEqual(set.count, 1)
    }

    func testRecordSubscriptCaseInsensitive() {
        var record = ADIFRecord()
        record.setField(name: "CALL", value: "W1AW")
        XCTAssertEqual(record["call"], "W1AW")
        XCTAssertEqual(record["Call"], "W1AW")
        XCTAssertEqual(record["CALL"], "W1AW")
    }

    func testRecordHasFieldCaseInsensitive() {
        var record = ADIFRecord()
        record.setField(name: "CALL", value: "W1AW")
        XCTAssertTrue(record.hasField("call"))
        XCTAssertTrue(record.hasField("CALL"))
        XCTAssertFalse(record.hasField("BAND"))
    }

    func testRecordAllFieldNamesSorted() {
        let fields = [
            ADIFField(name: "MODE", value: "FT8"),
            ADIFField(name: "CALL", value: "W1AW"),
            ADIFField(name: "BAND", value: "20m"),
        ]
        let record = ADIFRecord(fields: fields)
        XCTAssertEqual(record.allFieldNames, ["BAND", "CALL", "MODE"])
    }

    func testRecordSetAndRemove() {
        var record = ADIFRecord()
        record.setField(name: "CALL", value: "W1AW")
        XCTAssertEqual(record.fieldCount, 1)
        record.removeField(named: "call")
        XCTAssertTrue(record.isEmpty)
    }

    func testRecordDescription() {
        var record = ADIFRecord()
        record.setField(name: "CALL", value: "W1AW")
        let desc = record.description
        XCTAssertTrue(desc.contains("<CALL:4>W1AW"))
        XCTAssertTrue(desc.contains("<EOR>"))
    }

    func testFieldDescriptionWithType() {
        let field = ADIFField(name: "CALL", value: "W1AW", typeIndicator: "S")
        XCTAssertEqual(field.description, "<CALL:4:S>W1AW")
    }

    func testFieldDescriptionWithoutType() {
        let field = ADIFField(name: "CALL", value: "W1AW")
        XCTAssertEqual(field.description, "<CALL:4>W1AW")
    }

    func testDuplicateFieldNamesLastWins() {
        let adif = "<CALL:4>W1AW <CALL:5>VE3AB <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
        XCTAssertEqual(result.records[0]["CALL"], "VE3AB")
    }

    func testMultipleAppFieldsSameProgram() {
        let adif = "<CALL:4>W1AW <APP_HAMRD_QSO_ID:5>12345 <APP_HAMRD_COLOR:3>red <APP_HAMRD_FLAG:4>true <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records[0]["APP_HAMRD_QSO_ID"], "12345")
        XCTAssertEqual(result.records[0]["APP_HAMRD_COLOR"], "red")
        XCTAssertEqual(result.records[0]["APP_HAMRD_FLAG"], "true")
    }
}

// MARK: - Date/Time Tests

class ADIFDateTimeTests: XCTestCase {

    func testParseStandardDate() {
        let components = ADIFDateFormatter.parseDate("20240315")
        XCTAssertNotNil(components)
        XCTAssertEqual(components?.year, 2024)
        XCTAssertEqual(components?.month, 3)
        XCTAssertEqual(components?.day, 15)
    }

    func testParseStandardTimeWithSeconds() {
        let components = ADIFDateFormatter.parseTime("143022")
        XCTAssertNotNil(components)
        XCTAssertEqual(components?.hour, 14)
        XCTAssertEqual(components?.minute, 30)
        XCTAssertEqual(components?.second, 22)
    }

    func testParseShortTime() {
        let components = ADIFDateFormatter.parseTime("1430")
        XCTAssertNotNil(components)
        XCTAssertEqual(components?.hour, 14)
        XCTAssertEqual(components?.minute, 30)
        XCTAssertEqual(components?.second, 0)
    }

    func testInvalidDateMonth13() {
        let components = ADIFDateFormatter.parseDate("20241301")
        XCTAssertNil(components)
    }

    func testInvalidDateDay32() {
        let components = ADIFDateFormatter.parseDate("20240132")
        XCTAssertNil(components)
    }

    func testInvalidDateTooShort() {
        let components = ADIFDateFormatter.parseDate("202403")
        XCTAssertNil(components)
    }

    func testInvalidDateNonNumeric() {
        let components = ADIFDateFormatter.parseDate("2024031X")
        XCTAssertNil(components)
    }

    func testInvalidTimeHour25() {
        let components = ADIFDateFormatter.parseTime("250000")
        XCTAssertNil(components)
    }

    func testInvalidTimeMinute60() {
        let components = ADIFDateFormatter.parseTime("146000")
        XCTAssertNil(components)
    }

    func testInvalidTimeWrongLength() {
        let components = ADIFDateFormatter.parseTime("14300")
        XCTAssertNil(components)
    }

    func testDateTimeCombination() {
        let date = ADIFDateFormatter.parseDateTime(date: "20240315", time: "143022")
        XCTAssertNotNil(date)

        var cal = Calendar(identifier: .gregorian)
        cal.timeZone = TimeZone(identifier: "UTC")!
        XCTAssertEqual(cal.component(.year, from: date!), 2024)
        XCTAssertEqual(cal.component(.month, from: date!), 3)
        XCTAssertEqual(cal.component(.day, from: date!), 15)
        XCTAssertEqual(cal.component(.hour, from: date!), 14)
        XCTAssertEqual(cal.component(.minute, from: date!), 30)
        XCTAssertEqual(cal.component(.second, from: date!), 22)
    }

    func testDateTimeShort() {
        let date = ADIFDateFormatter.parseDateTime(date: "20240315", time: "1430")
        XCTAssertNotNil(date)
        var cal = Calendar(identifier: .gregorian)
        cal.timeZone = TimeZone(identifier: "UTC")!
        XCTAssertEqual(cal.component(.second, from: date!), 0)
    }

    func testDateTimeInvalidDate() {
        let date = ADIFDateFormatter.parseDateTime(date: "invalid", time: "143022")
        XCTAssertNil(date)
    }

    func testDateTimeInvalidTime() {
        let date = ADIFDateFormatter.parseDateTime(date: "20240315", time: "bad")
        XCTAssertNil(date)
    }

    func testFormatDate() {
        var cal = Calendar(identifier: .gregorian)
        cal.timeZone = TimeZone(identifier: "UTC")!
        var components = DateComponents()
        components.calendar = cal
        components.timeZone = TimeZone(identifier: "UTC")
        components.year = 2024
        components.month = 3
        components.day = 15
        components.hour = 14
        components.minute = 30
        components.second = 22
        let date = components.date!
        XCTAssertEqual(ADIFDateFormatter.formatDate(date), "20240315")
    }

    func testFormatTimeWithSeconds() {
        var cal = Calendar(identifier: .gregorian)
        cal.timeZone = TimeZone(identifier: "UTC")!
        var components = DateComponents()
        components.calendar = cal
        components.timeZone = TimeZone(identifier: "UTC")
        components.year = 2024
        components.month = 3
        components.day = 15
        components.hour = 14
        components.minute = 30
        components.second = 22
        let date = components.date!
        XCTAssertEqual(ADIFDateFormatter.formatTime(date, includeSeconds: true), "143022")
    }

    func testFormatTimeWithoutSeconds() {
        var cal = Calendar(identifier: .gregorian)
        cal.timeZone = TimeZone(identifier: "UTC")!
        var components = DateComponents()
        components.calendar = cal
        components.timeZone = TimeZone(identifier: "UTC")
        components.year = 2024
        components.month = 3
        components.day = 15
        components.hour = 14
        components.minute = 30
        components.second = 22
        let date = components.date!
        XCTAssertEqual(ADIFDateFormatter.formatTime(date, includeSeconds: false), "1430")
    }

    func testRoundTripDateFormat() {
        let original = "20240315"
        let components = ADIFDateFormatter.parseDate(original)!
        let date = components.date!
        let formatted = ADIFDateFormatter.formatDate(date)
        XCTAssertEqual(formatted, original)
    }

    func testRoundTripTimeFormat() {
        let original = "143022"
        let date = ADIFDateFormatter.parseDateTime(date: "20240315", time: original)!
        let formatted = ADIFDateFormatter.formatTime(date)
        XCTAssertEqual(formatted, original)
    }

    func testParseMidnightTime() {
        let components = ADIFDateFormatter.parseTime("000000")
        XCTAssertNotNil(components)
        XCTAssertEqual(components?.hour, 0)
        XCTAssertEqual(components?.minute, 0)
        XCTAssertEqual(components?.second, 0)
    }

    func testParseEndOfDayTime() {
        let components = ADIFDateFormatter.parseTime("235959")
        XCTAssertNotNil(components)
        XCTAssertEqual(components?.hour, 23)
        XCTAssertEqual(components?.minute, 59)
        XCTAssertEqual(components?.second, 59)
    }

    func testParseJan1() {
        let components = ADIFDateFormatter.parseDate("20240101")
        XCTAssertNotNil(components)
        XCTAssertEqual(components?.month, 1)
        XCTAssertEqual(components?.day, 1)
    }

    func testParseDec31() {
        let components = ADIFDateFormatter.parseDate("20241231")
        XCTAssertNotNil(components)
        XCTAssertEqual(components?.month, 12)
        XCTAssertEqual(components?.day, 31)
    }

    func testParseDateWhitespace() {
        let components = ADIFDateFormatter.parseDate("  20240315  ")
        XCTAssertNotNil(components)
        XCTAssertEqual(components?.year, 2024)
    }

    func testParseTimeWhitespace() {
        let components = ADIFDateFormatter.parseTime("  143022  ")
        XCTAssertNotNil(components)
        XCTAssertEqual(components?.hour, 14)
    }

    func testInvalidDateDay0() {
        let components = ADIFDateFormatter.parseDate("20240100")
        XCTAssertNil(components)
    }

    func testInvalidDateMonth0() {
        let components = ADIFDateFormatter.parseDate("20240015")
        XCTAssertNil(components)
    }

    func testEmptyDateString() {
        let components = ADIFDateFormatter.parseDate("")
        XCTAssertNil(components)
    }

    func testEmptyTimeString() {
        let components = ADIFDateFormatter.parseTime("")
        XCTAssertNil(components)
    }
}

// MARK: - Edge Cases

class ADIFEdgeCaseTests: XCTestCase {

    func testEmptyFile() {
        let result = ADIFParser.parse(string: "")
        XCTAssertNil(result.header)
        XCTAssertTrue(result.records.isEmpty)
        XCTAssertTrue(result.errors.isEmpty)
    }

    func testHeaderOnly() {
        let adif = "<ADIF_VER:5>3.1.4\n<PROGRAMID:7>TestApp\n<EOH>\n"
        let result = ADIFParser.parse(string: adif)
        XCTAssertNotNil(result.header)
        XCTAssertEqual(result.header?["ADIF_VER"], "3.1.4")
        XCTAssertTrue(result.records.isEmpty)
    }

    func testNoHeader() {
        let adif = "<CALL:4>W1AW <BAND:3>20m <EOR>\n<CALL:5>VE3AB <BAND:3>40m <EOR>\n"
        let result = ADIFParser.parse(string: adif)
        XCTAssertNil(result.header)
        XCTAssertEqual(result.records.count, 2)
    }

    func testWindowsCRLF() {
        let adif = "<ADIF_VER:5>3.1.4\r\n<EOH>\r\n<CALL:4>W1AW <BAND:3>20m <EOR>\r\n"
        let result = ADIFParser.parse(string: adif)
        XCTAssertNotNil(result.header)
        XCTAssertEqual(result.records.count, 1)
        XCTAssertEqual(result.records[0]["CALL"], "W1AW")
    }

    func testUnixLF() {
        let adif = "<ADIF_VER:5>3.1.4\n<EOH>\n<CALL:4>W1AW <BAND:3>20m <EOR>\n"
        let result = ADIFParser.parse(string: adif)
        XCTAssertNotNil(result.header)
        XCTAssertEqual(result.records.count, 1)
    }

    func testClassicMacCR() {
        let adif = "<ADIF_VER:5>3.1.4\r<EOH>\r<CALL:4>W1AW <BAND:3>20m <EOR>\r"
        let result = ADIFParser.parse(string: adif)
        XCTAssertNotNil(result.header)
        XCTAssertEqual(result.records.count, 1)
    }

    func testPreambleText() {
        let adif = """
        This is a preamble comment that appears before any tags.
        It can span multiple lines. Only text after '<' is parsed.
        <CALL:4>W1AW <BAND:3>20m <EOR>
        """
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
        XCTAssertEqual(result.records[0]["CALL"], "W1AW")
    }

    func testMultipleWhitespaceBetweenFields() {
        let adif = "<CALL:4>W1AW   \n\n   <BAND:3>20m\n\n\n<MODE:3>FT8   <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
        XCTAssertEqual(result.records[0]["CALL"], "W1AW")
        XCTAssertEqual(result.records[0]["BAND"], "20m")
        XCTAssertEqual(result.records[0]["MODE"], "FT8")
    }

    func testMinimalRecord() {
        let adif = "<CALL:4>W1AW <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
        XCTAssertEqual(result.records[0]["CALL"], "W1AW")
        XCTAssertEqual(result.records[0].fieldCount, 1)
    }

    func testVeryLargeFieldValue() {
        let longComment = String(repeating: "A", count: 1500)
        let adif = "<CALL:4>W1AW <COMMENT:\(longComment.count)>\(longComment) <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
        XCTAssertEqual(result.records[0]["COMMENT"], longComment)
    }

    func testUnicodeFieldValues() {
        let name = "Hans Müller"
        let adif = "<CALL:5>DL1AB <NAME:\(name.count)>\(name) <COMMENT:7>73 & ü <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
        XCTAssertEqual(result.records[0]["NAME"], name)
    }

    func testEmptyRecordSkipped() {
        let adif = "<CALL:4>W1AW <EOR><EOR><CALL:5>VE3AB <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 2)
        XCTAssertEqual(result.records[0]["CALL"], "W1AW")
        XCTAssertEqual(result.records[1]["CALL"], "VE3AB")
    }

    func testFieldWithNewlinesInValue() {
        let adif = "<CALL:4>W1AW <COMMENT:12>Line1\nLine2\n <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
        let comment = result.records[0]["COMMENT"]
        XCTAssertEqual(comment?.contains("\n"), true)
    }

    func testEohCaseInsensitive() {
        let adif = "<ADIF_VER:5>3.1.4\n<eoh>\n<CALL:4>W1AW <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertNotNil(result.header)
        XCTAssertEqual(result.records.count, 1)
    }

    func testEorCaseInsensitive() {
        let adif = "<CALL:4>W1AW <eor>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
    }

    func testMixedCaseEOHEOR() {
        let adif = "<ADIF_VER:5>3.1.4\n<Eoh>\n<CALL:4>W1AW <Eor>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertNotNil(result.header)
        XCTAssertEqual(result.records.count, 1)
    }

    func testWhitespaceOnlyFile() {
        let result = ADIFParser.parse(string: "   \n\n  \t  \n")
        XCTAssertTrue(result.records.isEmpty)
        XCTAssertNil(result.header)
    }

    func testOnlyPreambleNoTags() {
        let result = ADIFParser.parse(string: "This is just text with no ADIF tags whatsoever.")
        XCTAssertTrue(result.records.isEmpty)
        XCTAssertNil(result.header)
    }

    func testMultipleEOH() {
        let adif = "<ADIF_VER:5>3.1.4\n<EOH>\n<CALL:4>W1AW <EOH>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertNotNil(result.header)
    }

    func testTabsBetweenFields() {
        let adif = "<CALL:4>W1AW\t<BAND:3>20m\t<MODE:3>FT8\t<EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
        XCTAssertEqual(result.records[0]["CALL"], "W1AW")
    }

    func testFieldValueWithAngleBrackets() {
        let adif = "<CALL:4>W1AW <COMMENT:11>RST was >59 <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertTrue(result.records.count >= 1)
    }

    func testZeroLengthField() {
        let adif = "<CALL:4>W1AW <NOTES:0> <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records.count, 1)
        XCTAssertEqual(result.records[0]["NOTES"], "")
    }

    func testFieldNameWithUnderscores() {
        let adif = "<CALL:4>W1AW <MY_GRIDSQUARE:6>FN31ab <STATION_CALLSIGN:5>N0ONE <EOR>"
        let result = ADIFParser.parse(string: adif)
        XCTAssertEqual(result.records[0]["MY_GRIDSQUARE"], "FN31ab")
        XCTAssertEqual(result.records[0]["STATION_CALLSIGN"], "N0ONE")
    }
}

// MARK: - Error Handling

class ADIFErrorHandlingTests: XCTestCase {

    func testMalformedTagNoClosing() {
        let adif = "<CALL:4>W1AW <BAND:3 <MODE:3>FT8 <EOR>"
        let result = ADIFParser.parse(string: adif, mode: .lenient)
        XCTAssertFalse(result.warnings.isEmpty)
        XCTAssertTrue(result.records.count >= 1)
    }

    func testMissingLengthLenient() {
        let adif = "<CALL:4>W1AW <BAND>20m <MODE:3>FT8 <EOR>"
        let result = ADIFParser.parse(string: adif, mode: .lenient)
        XCTAssertFalse(result.warnings.isEmpty)
        XCTAssertTrue(result.records.count >= 1)
        XCTAssertEqual(result.records[0]["CALL"], "W1AW")
    }

    func testNonNumericLengthLenient() {
        let adif = "<CALL:4>W1AW <BAND:abc>20m <MODE:3>FT8 <EOR>"
        let result = ADIFParser.parse(string: adif, mode: .lenient)
        XCTAssertFalse(result.warnings.isEmpty)
        XCTAssertTrue(result.records.count >= 1)
    }

    func testStrictModeRejects() {
        let adif = "<CALL:4>W1AW <BAND>20m <MODE:3>FT8 <EOR>"
        let result = ADIFParser.parse(string: adif, mode: .strict)
        XCTAssertFalse(result.errors.isEmpty)
    }

    func testLenientModeContinues() {
        let adif = "<CALL:4>W1AW <BAD_TAG <EOR>\n<CALL:5>VE3AB <BAND:3>20m <EOR>"
        let result = ADIFParser.parse(string: adif, mode: .lenient)
        XCTAssertFalse(result.warnings.isEmpty)
        XCTAssertTrue(result.records.count >= 1)
    }

    func testNegativeLength() {
        let adif = "<CALL:-1>W1AW <EOR>"
        let result = ADIFParser.parse(string: adif, mode: .lenient)
        XCTAssertFalse(result.warnings.isEmpty)
    }

    func testZeroLengthFieldName() {
        let adif = "<:4>W1AW <EOR>"
        let result = ADIFParser.parse(string: adif, mode: .lenient)
        XCTAssertFalse(result.warnings.isEmpty)
    }

    func testEmptyTag() {
        let adif = "<> <CALL:4>W1AW <EOR>"
        let result = ADIFParser.parse(string: adif, mode: .lenient)
        XCTAssertTrue(result.records.count >= 1)
    }

    func testStrictModeStopsOnFirstError() {
        let adif = "<BAD <CALL:4>W1AW <EOR>\n<CALL:5>VE3AB <EOR>"
        let result = ADIFParser.parse(string: adif, mode: .strict)
        XCTAssertFalse(result.errors.isEmpty)
    }

    func testParseWarningDescription() {
        let warning = ADIFParser.ParseWarning(line: 42, message: "Bad field")
        XCTAssertTrue(warning.description.contains("42"))
        XCTAssertTrue(warning.description.contains("Bad field"))
    }

    func testParseWarningDescriptionNoLine() {
        let warning = ADIFParser.ParseWarning(message: "Bad field")
        XCTAssertEqual(warning.description, "Bad field")
    }

    func testParseErrorDescription() {
        let error = ADIFParser.ParseError(line: 10, message: "Fatal error")
        XCTAssertTrue(error.description.contains("10"))
    }

    func testParseErrorConformsToError() {
        let error: Error = ADIFParser.ParseError(line: 1, message: "test")
        XCTAssertTrue(error.localizedDescription.count > 0)
    }

    func testMultipleMalformedLenient() {
        let adif = """
        <CALL:4>W1AW <BAD <ALSO_BAD <BAND:3>20m <EOR>
        <CALL:5>VE3AB <NOLEN>data <MODE:3>SSB <EOR>
        """
        let result = ADIFParser.parse(string: adif, mode: .lenient)
        XCTAssertTrue(result.warnings.count >= 2)
        XCTAssertTrue(result.records.count >= 1)
    }

    func testUnclosedTagAtEnd() {
        let adif = "<CALL:4>W1AW <EOR>\n<CALL:5>VE3AB <UNCLOSED"
        let result = ADIFParser.parse(string: adif, mode: .lenient)
        XCTAssertTrue(result.records.count >= 1)
        XCTAssertFalse(result.warnings.isEmpty)
    }
}

// MARK: - Round-trip Tests

class ADIFRoundTripTests: XCTestCase {

    func testRoundTripBasic() {
        let original = """
        <ADIF_VER:5>3.1.4
        <PROGRAMID:14>HamStation Pro
        <EOH>
        <CALL:4>W1AW <BAND:3>20m <MODE:3>FT8 <QSO_DATE:8>20240315 <TIME_ON:6>143022 <RST_SENT:3>-10 <RST_RCVD:3>-08 <EOR>
        <CALL:5>VE3AB <BAND:3>40m <MODE:2>CW <QSO_DATE:8>20240315 <TIME_ON:6>150000 <RST_SENT:3>599 <RST_RCVD:3>579 <EOR>
        """

        let firstResult = ADIFParser.parse(string: original)
        XCTAssertEqual(firstResult.records.count, 2)

        let exported = ADIFExporter.export(
            records: firstResult.records,
            options: .init(includeHeader: false, lineEnding: "\n")
        )

        let secondResult = ADIFParser.parse(string: exported)
        XCTAssertEqual(secondResult.records.count, firstResult.records.count)

        for (i, record) in firstResult.records.enumerated() {
            let reRecord = secondResult.records[i]
            for name in record.allFieldNames {
                XCTAssertEqual(record[name], reRecord[name], "Field \(name) mismatch at record \(i)")
            }
        }
    }

    func testRoundTripAppFields() {
        let adif = "<CALL:4>W1AW <APP_HAMRD_QSO_ID:5>12345 <APP_N1MM_POINTS:1>2 <EOR>"
        let firstResult = ADIFParser.parse(string: adif)
        let exported = ADIFExporter.export(
            records: firstResult.records,
            options: .init(includeHeader: false, lineEnding: "\n")
        )
        let secondResult = ADIFParser.parse(string: exported)
        XCTAssertEqual(secondResult.records.count, 1)
        XCTAssertEqual(secondResult.records[0]["APP_HAMRD_QSO_ID"], "12345")
        XCTAssertEqual(secondResult.records[0]["APP_N1MM_POINTS"], "2")
    }

    func testRoundTripTypeIndicators() {
        let adif = "<CALL:4:S>W1AW <QSO_DATE:8:D>20240315 <FREQ:8:N>14.07400 <EOR>"
        let firstResult = ADIFParser.parse(string: adif)
        let exported = ADIFExporter.export(
            records: firstResult.records,
            options: .init(includeHeader: false, lineEnding: "\n")
        )
        let secondResult = ADIFParser.parse(string: exported)
        XCTAssertEqual(secondResult.records.count, 1)
        XCTAssertEqual(secondResult.records[0]["CALL"], "W1AW")
        let callField = secondResult.records[0].field(named: "CALL")
        XCTAssertEqual(callField?.typeIndicator, "S")
        let dateField = secondResult.records[0].field(named: "QSO_DATE")
        XCTAssertEqual(dateField?.typeIndicator, "D")
    }

    func testRoundTripManyFields() {
        var record = ADIFRecord()
        record.setField(ADIFField(name: "CALL", value: "W1AW"))
        record.setField(ADIFField(name: "BAND", value: "20m"))
        record.setField(ADIFField(name: "MODE", value: "FT8"))
        record.setField(ADIFField(name: "FREQ", value: "14.07400"))
        record.setField(ADIFField(name: "QSO_DATE", value: "20240315"))
        record.setField(ADIFField(name: "TIME_ON", value: "143022"))
        record.setField(ADIFField(name: "RST_SENT", value: "-10"))
        record.setField(ADIFField(name: "RST_RCVD", value: "-08"))
        record.setField(ADIFField(name: "TX_PWR", value: "50"))
        record.setField(ADIFField(name: "GRIDSQUARE", value: "FN31"))
        record.setField(ADIFField(name: "NAME", value: "John Doe"))
        record.setField(ADIFField(name: "COMMENT", value: "Great QSO!"))
        record.setField(ADIFField(name: "COUNTRY", value: "USA"))
        record.setField(ADIFField(name: "DXCC", value: "291"))
        record.setField(ADIFField(name: "CQZ", value: "5"))
        record.setField(ADIFField(name: "ITUZ", value: "8"))
        record.setField(ADIFField(name: "CONT", value: "NA"))

        let exported = ADIFExporter.export(
            records: [record],
            options: .init(includeHeader: false, lineEnding: "\n")
        )
        let result = ADIFParser.parse(string: exported)
        XCTAssertEqual(result.records.count, 1)

        for name in record.allFieldNames {
            XCTAssertEqual(result.records[0][name], record[name], "Field \(name) mismatch")
        }
    }

    func testRoundTripEmptyField() {
        let adif = "<CALL:4>W1AW <COMMENT:0> <EOR>"
        let firstResult = ADIFParser.parse(string: adif)
        let exported = ADIFExporter.export(
            records: firstResult.records,
            options: .init(includeHeader: false, lineEnding: "\n")
        )
        let secondResult = ADIFParser.parse(string: exported)
        XCTAssertEqual(secondResult.records[0]["COMMENT"], "")
    }

    func testRoundTripFieldCount() {
        let adif = "<CALL:4>W1AW <BAND:3>20m <MODE:3>FT8 <QSO_DATE:8>20240315 <TIME_ON:6>143022 <EOR>"
        let first = ADIFParser.parse(string: adif)
        let exported = ADIFExporter.export(records: first.records, options: .init(includeHeader: false, lineEnding: "\n"))
        let second = ADIFParser.parse(string: exported)
        XCTAssertEqual(first.records[0].fieldCount, second.records[0].fieldCount)
    }
}

// MARK: - Export Tests

class ADIFExportTests: XCTestCase {

    func testExportSingleRecord() {
        var record = ADIFRecord()
        record.setField(ADIFField(name: "CALL", value: "W1AW"))
        record.setField(ADIFField(name: "BAND", value: "20m"))

        let output = ADIFExporter.export(
            records: [record],
            options: .init(includeHeader: false, lineEnding: "\n")
        )
        XCTAssertTrue(output.contains("<CALL:4>W1AW"))
        XCTAssertTrue(output.contains("<BAND:3>20m"))
        XCTAssertTrue(output.contains("<EOR>"))
    }

    func testExportWithHeader() {
        let output = ADIFExporter.export(
            records: [],
            options: .init(includeHeader: true, programId: "TestApp", programVersion: "2.0", adifVersion: "3.1.4", lineEnding: "\n")
        )
        XCTAssertTrue(output.contains("<ADIF_VER:5>3.1.4"))
        XCTAssertTrue(output.contains("<PROGRAMID:7>TestApp"))
        XCTAssertTrue(output.contains("<PROGRAMVERSION:3>2.0"))
        XCTAssertTrue(output.contains("<EOH>"))
    }

    func testExportWithoutHeader() {
        var record = ADIFRecord()
        record.setField(ADIFField(name: "CALL", value: "W1AW"))

        let output = ADIFExporter.export(
            records: [record],
            options: .init(includeHeader: false, lineEnding: "\n")
        )
        XCTAssertFalse(output.contains("<EOH>"))
        XCTAssertFalse(output.contains("ADIF_VER"))
        XCTAssertTrue(output.contains("<CALL:4>W1AW"))
    }

    func testExportFieldOrderAlphabetical() {
        var record = ADIFRecord()
        record.setField(ADIFField(name: "MODE", value: "FT8"))
        record.setField(ADIFField(name: "CALL", value: "W1AW"))
        record.setField(ADIFField(name: "BAND", value: "20m"))

        let output = ADIFExporter.export(
            records: [record],
            options: .init(includeHeader: false, lineEnding: "\n")
        )
        let bandIdx = output.range(of: "BAND")!.lowerBound
        let callIdx = output.range(of: "CALL")!.lowerBound
        let modeIdx = output.range(of: "MODE")!.lowerBound
        XCTAssertTrue(bandIdx < callIdx)
        XCTAssertTrue(callIdx < modeIdx)
    }

    func testExportFieldOrderCustom() {
        var record = ADIFRecord()
        record.setField(ADIFField(name: "MODE", value: "FT8"))
        record.setField(ADIFField(name: "CALL", value: "W1AW"))
        record.setField(ADIFField(name: "BAND", value: "20m"))

        let output = ADIFExporter.export(
            records: [record],
            options: .init(includeHeader: false, lineEnding: "\n", fieldOrder: ["CALL", "BAND", "MODE"])
        )
        let callIdx = output.range(of: "CALL")!.lowerBound
        let bandIdx = output.range(of: "BAND")!.lowerBound
        let modeIdx = output.range(of: "MODE")!.lowerBound
        XCTAssertTrue(callIdx < bandIdx)
        XCTAssertTrue(bandIdx < modeIdx)
    }

    func testExportAppFields() {
        var record = ADIFRecord()
        record.setField(ADIFField(name: "CALL", value: "W1AW"))
        record.setField(ADIFField(name: "APP_HAMRD_QSO_ID", value: "12345"))

        let output = ADIFExporter.export(
            records: [record],
            options: .init(includeHeader: false, lineEnding: "\n")
        )
        XCTAssertTrue(output.contains("<APP_HAMRD_QSO_ID:5>12345"))
    }

    func testExportTypeIndicator() {
        let field = ADIFField(name: "CALL", value: "W1AW", typeIndicator: "S")
        let exported = ADIFExporter.exportField(field)
        XCTAssertEqual(exported, "<CALL:4:S>W1AW")
    }

    func testExportNoTypeIndicator() {
        let field = ADIFField(name: "CALL", value: "W1AW")
        let exported = ADIFExporter.exportField(field)
        XCTAssertEqual(exported, "<CALL:4>W1AW")
    }

    func testExportCRLFDefault() {
        var record = ADIFRecord()
        record.setField(ADIFField(name: "CALL", value: "W1AW"))
        let output = ADIFExporter.export(records: [record])
        XCTAssertTrue(output.contains("\r\n"))
    }

    func testExportCustomLineEnding() {
        var record = ADIFRecord()
        record.setField(ADIFField(name: "CALL", value: "W1AW"))
        let output = ADIFExporter.export(
            records: [record],
            options: .init(lineEnding: "\n")
        )
        XCTAssertFalse(output.contains("\r\n"))
        XCTAssertTrue(output.contains("\n"))
    }

    func testExportMultipleRecords() {
        var r1 = ADIFRecord()
        r1.setField(ADIFField(name: "CALL", value: "W1AW"))
        var r2 = ADIFRecord()
        r2.setField(ADIFField(name: "CALL", value: "VE3AB"))

        let output = ADIFExporter.export(
            records: [r1, r2],
            options: .init(includeHeader: false, lineEnding: "\n")
        )
        let eorCount = output.components(separatedBy: "<EOR>").count - 1
        XCTAssertEqual(eorCount, 2)
    }

    func testExportEmptyFieldValue() {
        let field = ADIFField(name: "COMMENT", value: "")
        let exported = ADIFExporter.exportField(field)
        XCTAssertEqual(exported, "<COMMENT:0>")
    }

    func testExportEmptyRecords() {
        let output = ADIFExporter.export(records: [], options: .init(includeHeader: true, lineEnding: "\n"))
        XCTAssertTrue(output.contains("<EOH>"))
        XCTAssertFalse(output.contains("<EOR>"))
    }

    func testExportToFile() throws {
        let tempDir = FileManager.default.temporaryDirectory
        let fileURL = tempDir.appendingPathComponent("test_export_\(UUID()).adi")
        defer { try? FileManager.default.removeItem(at: fileURL) }

        var record = ADIFRecord()
        record.setField(ADIFField(name: "CALL", value: "W1AW"))
        record.setField(ADIFField(name: "BAND", value: "20m"))

        try ADIFExporter.export(records: [record], to: fileURL)

        let readBack = try String(contentsOf: fileURL, encoding: .utf8)
        XCTAssertTrue(readBack.contains("<CALL:4>W1AW"))
        XCTAssertTrue(readBack.contains("<EOR>"))
    }

    func testExportOptionsDefaults() {
        let opts = ADIFExporter.ExportOptions()
        XCTAssertEqual(opts.includeHeader, true)
        XCTAssertEqual(opts.programId, "HamStation Pro")
        XCTAssertEqual(opts.programVersion, "1.0")
        XCTAssertEqual(opts.adifVersion, "3.1.4")
        XCTAssertEqual(opts.lineEnding, "\r\n")
        XCTAssertNil(opts.fieldOrder)
    }

    func testCustomFieldOrderWithExtras() {
        var record = ADIFRecord()
        record.setField(ADIFField(name: "MODE", value: "FT8"))
        record.setField(ADIFField(name: "CALL", value: "W1AW"))
        record.setField(ADIFField(name: "BAND", value: "20m"))
        record.setField(ADIFField(name: "COMMENT", value: "test"))

        let output = ADIFExporter.export(
            records: [record],
            options: .init(includeHeader: false, lineEnding: "\n", fieldOrder: ["CALL", "BAND"])
        )
        let callIdx = output.range(of: "CALL")!.lowerBound
        let bandIdx = output.range(of: "BAND")!.lowerBound
        XCTAssertTrue(callIdx < bandIdx)
        let commentIdx = output.range(of: "COMMENT")!.lowerBound
        XCTAssertTrue(bandIdx < commentIdx)
    }
}

// MARK: - Fixture File Tests

class ADIFFixtureFileTests: XCTestCase {

    func fixtureURL(_ name: String) -> URL? {
        Bundle.module.url(forResource: name, withExtension: "adi", subdirectory: "Fixtures")
    }

    func testParseSimpleFixture() throws {
        guard let url = fixtureURL("simple") else {
            XCTFail("simple.adi fixture not found")
            return
        }
        let result = try ADIFParser.parse(url: url)
        XCTAssertNotNil(result.header)
        XCTAssertEqual(result.header?["ADIF_VER"], "3.1.4")
        XCTAssertEqual(result.header?["PROGRAMID"], "HamStation Pro")
        XCTAssertEqual(result.records.count, 5)
        XCTAssertEqual(result.records[0]["CALL"], "W1AW")
        XCTAssertEqual(result.records[0]["MODE"], "FT8")
        XCTAssertEqual(result.records[1]["CALL"], "VE3AB")
        XCTAssertEqual(result.records[1]["MODE"], "CW")
        XCTAssertEqual(result.records[2]["MODE"], "SSB")
        XCTAssertEqual(result.records[3]["CALL"], "JA1ABC")
        XCTAssertEqual(result.records[4]["CALL"], "ZL1AA")
        XCTAssertTrue(result.errors.isEmpty)
    }

    func testParseNoHeaderFixture() throws {
        guard let url = fixtureURL("no_header") else {
            XCTFail("no_header.adi fixture not found")
            return
        }
        let result = try ADIFParser.parse(url: url)
        XCTAssertNil(result.header)
        XCTAssertEqual(result.records.count, 3)
        XCTAssertEqual(result.records[0]["CALL"], "W1AW")
        XCTAssertEqual(result.records[1]["CALL"], "K3LR0")
        XCTAssertEqual(result.records[2]["CALL"], "VK2ABC")
    }

    func testParseAppFieldsFixture() throws {
        guard let url = fixtureURL("app_fields") else {
            XCTFail("app_fields.adi fixture not found")
            return
        }
        let result = try ADIFParser.parse(url: url)
        XCTAssertNotNil(result.header)
        XCTAssertEqual(result.records.count, 3)
        XCTAssertEqual(result.records[0]["APP_HAMRD_QSO_ID"], "12345")
        XCTAssertEqual(result.records[0]["APP_HAMRD_COLOR"], "red")
        XCTAssertEqual(result.records[1]["APP_N1MM_POINTS"], "2")
        XCTAssertEqual(result.records[1]["APP_N1MM_SECTION"], "EPA")
    }

    func testParseMalformedFixtureLenient() throws {
        guard let url = fixtureURL("malformed") else {
            XCTFail("malformed.adi fixture not found")
            return
        }
        let result = try ADIFParser.parse(url: url, mode: .lenient)
        XCTAssertFalse(result.warnings.isEmpty)
        XCTAssertTrue(result.records.count >= 1)
    }

    func testParseMalformedFixtureStrict() throws {
        guard let url = fixtureURL("malformed") else {
            XCTFail("malformed.adi fixture not found")
            return
        }
        let result = try ADIFParser.parse(url: url, mode: .strict)
        XCTAssertTrue(result.records.count >= 1)
    }

    func testParseWSJTXFixture() throws {
        guard let url = fixtureURL("wsjt_x_sample") else {
            XCTFail("wsjt_x_sample.adi fixture not found")
            return
        }
        let result = try ADIFParser.parse(url: url)
        XCTAssertNotNil(result.header)
        XCTAssertEqual(result.header?["PROGRAMID"], "WSJT-X")
        XCTAssertEqual(result.header?["PROGRAMVERSION"], "2.7.0")
        XCTAssertEqual(result.records.count, 5)
        for record in result.records {
            XCTAssertEqual(record["MODE"], "FT8")
            XCTAssertTrue(record.hasField("STATION_CALLSIGN"))
            XCTAssertTrue(record.hasField("MY_GRIDSQUARE"))
        }
        XCTAssertEqual(result.records[0]["STATION_CALLSIGN"], "N0ONE")
        XCTAssertEqual(result.records[0]["MY_GRIDSQUARE"], "EM48nf")
    }

    func testRoundTripSimpleFixture() throws {
        guard let url = fixtureURL("simple") else {
            XCTFail("simple.adi fixture not found")
            return
        }
        let first = try ADIFParser.parse(url: url)
        let exported = ADIFExporter.export(
            records: first.records,
            options: .init(includeHeader: false, lineEnding: "\n")
        )
        let second = ADIFParser.parse(string: exported)
        XCTAssertEqual(first.records.count, second.records.count)
        for (i, record) in first.records.enumerated() {
            for name in record.allFieldNames {
                XCTAssertEqual(record[name], second.records[i][name], "Mismatch at record \(i), field \(name)")
            }
        }
    }

    func testRoundTripAppFieldsFixture() throws {
        guard let url = fixtureURL("app_fields") else {
            XCTFail("app_fields.adi fixture not found")
            return
        }
        let first = try ADIFParser.parse(url: url)
        let exported = ADIFExporter.export(
            records: first.records,
            options: .init(includeHeader: false, lineEnding: "\n")
        )
        let second = ADIFParser.parse(string: exported)
        XCTAssertEqual(first.records.count, second.records.count)
        XCTAssertEqual(second.records[0]["APP_HAMRD_QSO_ID"], "12345")
        XCTAssertEqual(second.records[1]["APP_N1MM_POINTS"], "2")
    }
}

// MARK: - Streaming Parser Tests

class ADIFStreamingParserTests: XCTestCase {

    func testStreamParseRecordCount() async throws {
        let tempDir = FileManager.default.temporaryDirectory
        let fileURL = tempDir.appendingPathComponent("stream_test_\(UUID()).adi")
        defer { try? FileManager.default.removeItem(at: fileURL) }

        let adif = """
        <ADIF_VER:5>3.1.4
        <EOH>
        <CALL:4>W1AW <BAND:3>20m <EOR>
        <CALL:5>VE3AB <BAND:3>40m <EOR>
        <CALL:5>G3XYZ <BAND:3>15m <EOR>
        """
        try adif.write(to: fileURL, atomically: true, encoding: .utf8)

        var records: [ADIFRecord] = []
        let stream = ADIFParser.parseStream(url: fileURL)
        for try await record in stream {
            records.append(record)
        }
        // Header + 3 records = 4 yields (header is yielded as first record)
        XCTAssertEqual(records.count, 4)
    }

    func testStreamParseFileNotFound() async {
        let fakeURL = URL(fileURLWithPath: "/nonexistent/file.adi")
        let stream = ADIFParser.parseStream(url: fakeURL)
        var didThrow = false
        do {
            for try await _ in stream {
                // Should not get here
            }
        } catch {
            didThrow = true
        }
        XCTAssertTrue(didThrow)
    }
}

// MARK: - Parse URL Tests

class ADIFFileParsingTests: XCTestCase {

    func testParseFromURL() throws {
        let tempDir = FileManager.default.temporaryDirectory
        let fileURL = tempDir.appendingPathComponent("parse_url_test_\(UUID()).adi")
        defer { try? FileManager.default.removeItem(at: fileURL) }

        let adif = "<CALL:4>W1AW <BAND:3>20m <EOR>\n<CALL:5>VE3AB <BAND:3>40m <EOR>\n"
        try adif.write(to: fileURL, atomically: true, encoding: .utf8)

        let result = try ADIFParser.parse(url: fileURL)
        XCTAssertEqual(result.records.count, 2)
    }

    func testParseNonexistentFile() {
        let fakeURL = URL(fileURLWithPath: "/nonexistent/file.adi")
        XCTAssertThrowsError(try ADIFParser.parse(url: fakeURL))
    }
}

// MARK: - Performance Tests

class ADIFPerformanceTests: XCTestCase {

    func testParse10kRecords() {
        var adif = "<ADIF_VER:5>3.1.4\n<EOH>\n"
        for i in 0..<10_000 {
            let call = String(format: "W%04dAA", i)
            let date = "20240315"
            let time = String(format: "%02d%02d00", (i / 60) % 24, i % 60)
            adif += "<CALL:\(call.count)>\(call) <BAND:3>20m <MODE:3>FT8 "
            adif += "<QSO_DATE:8>\(date) <TIME_ON:6>\(time) "
            adif += "<RST_SENT:3>-10 <RST_RCVD:3>-08 "
            adif += "<GRIDSQUARE:4>FN31 <TX_PWR:2>50 <EOR>\n"
        }

        let start = ContinuousClock.now
        let result = ADIFParser.parse(string: adif)
        let elapsed = ContinuousClock.now - start

        XCTAssertEqual(result.records.count, 10_000)
        XCTAssertNotNil(result.header)
        XCTAssertTrue(result.errors.isEmpty)
        XCTAssertTrue(elapsed < .seconds(10), "Parsing 10k records took \(elapsed)")
    }

    func testExport10kRecords() {
        var records: [ADIFRecord] = []
        for i in 0..<10_000 {
            var record = ADIFRecord()
            record.setField(ADIFField(name: "CALL", value: String(format: "W%04dAA", i)))
            record.setField(ADIFField(name: "BAND", value: "20m"))
            record.setField(ADIFField(name: "MODE", value: "FT8"))
            record.setField(ADIFField(name: "QSO_DATE", value: "20240315"))
            record.setField(ADIFField(name: "TIME_ON", value: String(format: "%02d%02d00", (i / 60) % 24, i % 60)))
            records.append(record)
        }

        let start = ContinuousClock.now
        let output = ADIFExporter.export(records: records, options: .init(lineEnding: "\n"))
        let elapsed = ContinuousClock.now - start

        XCTAssertTrue(output.count > 0)
        XCTAssertTrue(elapsed < .seconds(5), "Exporting 10k records took \(elapsed)")
    }

    func testRoundTrip1kRecords() {
        var adif = "<ADIF_VER:5>3.1.4\n<EOH>\n"
        for i in 0..<1_000 {
            let call = String(format: "K%03dAB", i)
            adif += "<CALL:\(call.count)>\(call) <BAND:3>20m <MODE:2>CW "
            adif += "<QSO_DATE:8>20240315 <TIME_ON:6>120000 <RST_SENT:3>599 <RST_RCVD:3>579 "
            adif += "<GRIDSQUARE:6>FN31ab <TX_PWR:3>100 <COMMENT:4>test <EOR>\n"
        }

        let first = ADIFParser.parse(string: adif)
        XCTAssertEqual(first.records.count, 1_000)

        let exported = ADIFExporter.export(records: first.records, options: .init(includeHeader: false, lineEnding: "\n"))
        let second = ADIFParser.parse(string: exported)
        XCTAssertEqual(second.records.count, 1_000)

        XCTAssertEqual(first.records[0]["CALL"], second.records[0]["CALL"])
        XCTAssertEqual(first.records[500]["CALL"], second.records[500]["CALL"])
        XCTAssertEqual(first.records[999]["CALL"], second.records[999]["CALL"])
    }
}

// MARK: - Sendable Conformance Tests

class ADIFSendableTests: XCTestCase {

    func testFieldSendable() async {
        let field = ADIFField(name: "CALL", value: "W1AW")
        let task = Task { field.name }
        let name = await task.value
        XCTAssertEqual(name, "CALL")
    }

    func testRecordSendable() async {
        var record = ADIFRecord()
        record.setField(ADIFField(name: "CALL", value: "W1AW"))
        let task = Task { record["CALL"] }
        let value = await task.value
        XCTAssertEqual(value, "W1AW")
    }

    func testParseResultSendable() async {
        let result = ADIFParser.ParseResult(records: [])
        let task = Task { result.records.count }
        let count = await task.value
        XCTAssertEqual(count, 0)
    }

    func testWarningIsSendable() async {
        let warning = ADIFParser.ParseWarning(line: 1, message: "test")
        let task = Task { warning.message }
        let msg = await task.value
        XCTAssertEqual(msg, "test")
    }

    func testErrorIsSendable() async {
        let error = ADIFParser.ParseError(line: 1, message: "test")
        let task = Task { error.message }
        let msg = await task.value
        XCTAssertEqual(msg, "test")
    }

    func testExportOptionsSendable() async {
        let opts = ADIFExporter.ExportOptions()
        let task = Task { opts.programId }
        let pid = await task.value
        XCTAssertEqual(pid, "HamStation Pro")
    }
}

// MARK: - ADIFRecord Initializer Tests

class ADIFRecordInitTests: XCTestCase {

    func testInitFromArray() {
        let fields = [
            ADIFField(name: "CALL", value: "W1AW"),
            ADIFField(name: "BAND", value: "20m"),
        ]
        let record = ADIFRecord(fields: fields)
        XCTAssertEqual(record["CALL"], "W1AW")
        XCTAssertEqual(record["BAND"], "20m")
        XCTAssertEqual(record.fieldCount, 2)
    }

    func testInitFromDict() {
        let fields: [String: ADIFField] = [
            "CALL": ADIFField(name: "CALL", value: "W1AW"),
            "BAND": ADIFField(name: "BAND", value: "20m"),
        ]
        let record = ADIFRecord(fields: fields)
        XCTAssertEqual(record["CALL"], "W1AW")
        XCTAssertEqual(record.fieldCount, 2)
    }

    func testInitEmpty() {
        let record = ADIFRecord()
        XCTAssertTrue(record.isEmpty)
        XCTAssertEqual(record.fieldCount, 0)
        XCTAssertTrue(record.allFieldNames.isEmpty)
    }

    func testInitFromArrayDuplicates() {
        let fields = [
            ADIFField(name: "CALL", value: "W1AW"),
            ADIFField(name: "CALL", value: "VE3AB"),
        ]
        let record = ADIFRecord(fields: fields)
        XCTAssertEqual(record["CALL"], "VE3AB")
        XCTAssertEqual(record.fieldCount, 1)
    }
}
