// ADIFExporter.swift
// HamStationKit — ADIF 3.1 Parser & Exporter
//
// Exports QSO records to ADIF 3.1 format.

import Foundation

/// Exports `ADIFRecord` values to ADIF 3.1 format strings or files.
public enum ADIFExporter: Sendable {

    // MARK: - Options

    /// Configuration options for ADIF export.
    public struct ExportOptions: Sendable {
        /// Whether to include the ADIF header. Default `true`.
        public var includeHeader: Bool
        /// The program identifier written to the header. Default `"HamStation Pro"`.
        public var programId: String
        /// The program version written to the header. Default `"1.0"`.
        public var programVersion: String
        /// The ADIF version string. Default `"3.1.4"`.
        public var adifVersion: String
        /// Line ending to use. Default `"\r\n"` (ADIF standard).
        public var lineEnding: String
        /// If non-nil, export fields in this order (unmatched fields appended
        /// alphabetically). If `nil`, all fields are alphabetical.
        public var fieldOrder: [String]?

        public init(
            includeHeader: Bool = true,
            programId: String = "HamStation Pro",
            programVersion: String = "1.0",
            adifVersion: String = "3.1.4",
            lineEnding: String = "\r\n",
            fieldOrder: [String]? = nil
        ) {
            self.includeHeader = includeHeader
            self.programId = programId
            self.programVersion = programVersion
            self.adifVersion = adifVersion
            self.lineEnding = lineEnding
            self.fieldOrder = fieldOrder
        }
    }

    // MARK: - Public API

    /// Exports an array of QSO records to an ADIF string.
    ///
    /// - Parameters:
    ///   - records: The QSO records to export.
    ///   - options: Export options (default values produce standard ADIF).
    /// - Returns: A complete ADIF string.
    public static func export(
        records: [ADIFRecord],
        options: ExportOptions = .init()
    ) -> String {
        var output = ""
        output.reserveCapacity(records.count * 200) // rough estimate

        if options.includeHeader {
            output += exportHeader(options: options)
        }

        for record in records {
            output += exportRecord(record, options: options)
        }

        return output
    }

    /// Exports an array of QSO records to an ADIF file.
    ///
    /// - Parameters:
    ///   - records: The QSO records to export.
    ///   - url: The file URL to write to.
    ///   - options: Export options.
    /// - Throws: If the file cannot be written.
    public static func export(
        records: [ADIFRecord],
        to url: URL,
        options: ExportOptions = .init()
    ) throws {
        let string = export(records: records, options: options)
        try string.write(to: url, atomically: true, encoding: .utf8)
    }

    /// Exports a single ADIF field to its string representation.
    ///
    /// - Parameter field: The field to export.
    /// - Returns: A string like `<CALL:4>W1AW` or `<CALL:4:S>W1AW`.
    public static func exportField(_ field: ADIFField) -> String {
        let length = field.value.count
        if let type = field.typeIndicator, !type.isEmpty {
            return "<\(field.name):\(length):\(type)>\(field.value)"
        }
        return "<\(field.name):\(length)>\(field.value)"
    }

    // MARK: - Internal

    /// Produces the ADIF file header string.
    static func exportHeader(options: ExportOptions) -> String {
        let le = options.lineEnding
        var header = "Generated by \(options.programId) v\(options.programVersion)\(le)"
        header += exportField(ADIFField(name: "ADIF_VER", value: options.adifVersion)) + le
        header += exportField(ADIFField(name: "PROGRAMID", value: options.programId)) + le
        header += exportField(ADIFField(name: "PROGRAMVERSION", value: options.programVersion)) + le
        header += "<EOH>\(le)"
        return header
    }

    /// Exports a single record (its fields + `<EOR>`).
    static func exportRecord(_ record: ADIFRecord, options: ExportOptions) -> String {
        let le = options.lineEnding
        let orderedNames = orderedFieldNames(for: record, order: options.fieldOrder)

        var line = ""
        for name in orderedNames {
            if let field = record.fields[name] {
                line += exportField(field) + " "
            }
        }
        line += "<EOR>\(le)"
        return line
    }

    /// Determines field output order.
    private static func orderedFieldNames(
        for record: ADIFRecord,
        order: [String]?
    ) -> [String] {
        guard let order else {
            return record.allFieldNames // already sorted alphabetically
        }

        let upperOrder = order.map { $0.uppercased() }
        let allNames = Set(record.fields.keys)
        var result: [String] = []

        // First: fields in the specified order (if present in record)
        for name in upperOrder where allNames.contains(name) {
            result.append(name)
        }

        // Then: remaining fields alphabetically
        let ordered = Set(upperOrder)
        let remaining = allNames.subtracting(ordered).sorted()
        result.append(contentsOf: remaining)

        return result
    }
}
